// Consolidated Tailwind v4 JIT Engine
import { effect as _effect } from './reactivity.ts';
import { RuntimeContext } from './composition.ts';

// ============================================================================
// 1. AOT-INJECTED STYLE LAYER CONSTANTS
// ============================================================================
// Imported from manifest.ts which is fully auto-generated by scripts/build.ts.
// build.ts fetches preflight and theme from official Tailwind v4 CDN (jsDelivr),
// packs them into single-line escaped string constants, and emits them as
// exports into manifest.ts. Zero raw CSS strings live in this source file.
import {
  PACKED_PREFLIGHT,
  PACKED_THEME,
  PACKED_COMPONENTS,
  PACKED_KEYFRAMES,
} from '../manifest.ts';

/** @deprecated Use PACKED_THEME from manifest.ts */
export const THEME_CSS = PACKED_THEME;
/** @deprecated Use PACKED_COMPONENTS from manifest.ts */
export const PREFLIGHT_CSS = PACKED_COMPONENTS;
export { PACKED_THEME, PACKED_COMPONENTS };

// ============================================================================
// 2. CORE ENGINE (Types, Parser, CSS Generation)
// ============================================================================

// deno-lint-ignore-file no-explicit-any

export interface ASTNode {
  kind: 'declaration' | 'rule' | 'at-rule' | 'at-root';
  property?: string;
  value?: string;
  important?: boolean;
  selector?: string;
  nodes?: ASTNode[];
  name?: string;
  params?: string;
}

export interface ValueNode {
  kind: 'named' | 'arbitrary' | 'color';
  value: string;
}

export interface Candidate {
  kind: 'static' | 'functional' | 'arbitrary';
  root: string;
  value?: ValueNode;
  modifier?: ValueNode | null;
  property?: string; // For arbitrary properties [prop:val]
  variants: string[];
  important: boolean;
  negative: boolean;
  raw: string;
  hasSignal?: string;
}

export type CompileFn = (candidate: Candidate, ds: DesignSystem) => ASTNode[] | undefined;

interface Registry {
  static: Map<string, CompileFn[]>;
  functional: Map<string, { compileFn: CompileFn; options?: Record<string, unknown> }[]>;
}

interface VariantRegistry {
  static: Map<string, ASTNode[]>;
  functional: Map<string, { compileFn: CompileFn; options?: Record<string, unknown> }>;
  compound: Map<string, { root: string; variant: string; options?: Record<string, unknown> }>;
}

/**
 * DesignSystem — Native Singleton Engine mapping classes to AST nodes.
 * Explicitly avoids unifiedRef to prevent ZCZS serialization of functional handlers.
 */
export class DesignSystem {
  private _utilities: Registry = {
    static: new Map(),
    functional: new Map()
  };

  private _variants: VariantRegistry = {
    static: new Map(),
    functional: new Map(),
    compound: new Map()
  };

  static(this: DesignSystem, root: string, compileFn: CompileFn, _options?: Record<string, unknown>): void {
    this._utilities.static.set(root, (this._utilities.static.get(root) || []).concat([compileFn]));
  }

  functional(this: DesignSystem, root: string, compileFn: CompileFn, _options?: Record<string, unknown>): void {
    this._utilities.functional.set(root, (this._utilities.functional.get(root) || []).concat([{ compileFn, options: _options }]));
  }

  variant(name: string, definition: ASTNode[] | CompileFn) {
    if (typeof definition === 'function') {
      this._variants.functional.set(name, { compileFn: definition });
    } else {
      this._variants.static.set(name, definition);
    }
  }

  /**
   * Registers a custom component or utility rule dynamically.
   * Matches Tailwind v4 @utility and @layer components behavior.
   */
  registerCustomRule(root: string, cssText: string) {
    this.static(root, (candidate) => {
      // Return a rule node that directly contains the custom CSS
      // We wrap it in a pseudo-node that serializeAST can handle
      return [{
        kind: 'at-root',
        selector: `.${candidate.raw.replace(/([\[\]/!:#.])/g, '\\$1')}`,
        nodes: [{ kind: 'declaration', property: 'raw', value: cssText }]
      }];
    });
  }

  has(name: string, kind: 'static' | 'functional'): boolean {
    return kind === 'static' ? this._utilities.static.has(name) : this._utilities.functional.has(name);
  }

  getStatic(name: string) {
    return this._utilities.static.get(name) || [];
  }

  getFunctional(name: string) {
    return this._utilities.functional.get(name) || [];
  }

  parseVariant(name: string): ASTNode[] | null {
    if (this._variants.static.has(name)) return this._variants.static.get(name)!;
    if (this._variants.functional.has(name)) {
      return this._variants.functional.get(name)!.compileFn({ kind: 'static', root: name, variants: [], important: false, negative: false, raw: name }, this) || null;
    }
    return null;
  }

  *parseCandidate(raw: string): Generator<Candidate> {
    const variants: string[] = [];
    let important = false;
    let negative = false;
    let baseTerm = raw;

    if (baseTerm.endsWith('!')) {
       baseTerm = baseTerm.slice(0, -1);
       important = true;
    }
    
    const parts = baseTerm.split(':');
    baseTerm = parts.pop() || '';
    variants.push(...parts);

    if (baseTerm.startsWith('-')) {
       baseTerm = baseTerm.slice(1);
       negative = true;
    }

    // Arbitrary property [prop:value]
    if (baseTerm.startsWith('[') && baseTerm.endsWith(']')) {
      const content = baseTerm.slice(1, -1);
      const colonIndex = content.indexOf(':');
      if (colonIndex > 0) {
        yield {
          kind: 'arbitrary',
          root: '',
          property: content.slice(0, colonIndex),
          value: { kind: 'arbitrary', value: content.slice(colonIndex + 1).replace(/_/g, ' ') },
          variants,
          important,
          negative,
          raw
        };
        return;
      }
    }

    const slashParts = contextAwareSplit(baseTerm, '/');
    let term = slashParts[0];
    const modifierValue = slashParts[1] || null;

    // Fraction detection: w-1/2
    if (modifierValue && /^\d+$/.test(modifierValue)) {
      const lastDash = term.lastIndexOf('-');
      if (lastDash > 0) {
        const possibleNum = term.slice(lastDash + 1);
        if (/^\d+$/.test(possibleNum)) {
          term = term.slice(0, lastDash) + '-' + `${possibleNum}/${modifierValue}`;
        }
      }
    }

    // Bracket value functional match?
    let valNode: ValueNode | undefined = undefined;
    let hasSignal: string | undefined = undefined;
    if (term.includes('[') && term.endsWith(']')) {
       const bStart = term.indexOf('[');
       const inside = term.slice(bStart + 1, -1);
       if (/^[#a-zA-Z_$][\w$#.]*$/.test(inside)) {
          hasSignal = inside;
          const varName = inside.replace(/[#.]/g, '-');
          valNode = { kind: 'named', value: `var(--nx-${varName})` };
       } else {
          valNode = { kind: 'named', value: inside.replace(/_/g, ' ') };
       }
    }

    if (this.has(term, 'static')) {
      yield { kind: 'static', root: term, variants, important, negative, raw, hasSignal };
      return; 
    }

    // Functional parsing iterative lookup
    if (!valNode) {
      const parts = term.split('-');
      for (let i = parts.length; i >= 1; i--) {
        const root = parts.slice(0, i).join('-');
        const value = parts.slice(i).join('-');
        
        if (this.has(root, 'functional')) {
          yield {
            kind: 'functional',
            root,
            value: value ? { kind: 'named', value } : undefined,
            modifier: modifierValue ? { kind: 'named', value: modifierValue } : null,
            variants,
            important,
            negative,
            raw,
            hasSignal
          };
          if (value || i === parts.length) return; // Matched, and it's the longest root
        }
      }
    } else {
      const bIdx = term.indexOf('[');
      const root = bIdx > 0 ? (term[bIdx-1] === '-' ? term.slice(0, bIdx - 1) : term.slice(0, bIdx)) : term.slice(0, bIdx);
      if (this.has(root, 'functional')) {
        yield {
          kind: 'functional',
          root,
          value: valNode,
          modifier: modifierValue ? { kind: 'named', value: modifierValue } : null,
          variants,
          important,
          negative,
          raw,
          hasSignal
        };
      }
    }
  }

  generateCSS(candidate: Candidate): string {
    const nodes: ASTNode[] = [];
    
    if (candidate.kind === 'static') {
      const fns = this.getStatic(candidate.root);
      for (const fn of fns) {
        const result = fn(candidate, this);
        if (result) nodes.push(...result);
      }
    } else if (candidate.kind === 'functional') {
      const registry = this.getFunctional(candidate.root);
      for (const item of registry) {
        if (typeof item.compileFn !== 'function') {
          console.error(`[FATAL] JIT Crash on "${candidate.root}": item.compileFn is NOT a function! Item structure:`, item);
          console.error(`[FATAL] Full functional registry for ${candidate.root}:`, registry);
        }
        
        const result = item.compileFn(candidate, this);
        if (result) nodes.push(...result);
      }
    } else if (candidate.kind === 'arbitrary') {
      const v = typeof candidate.value === 'object' ? candidate.value.value : (candidate.value || '');
      nodes.push({
        kind: 'declaration',
        property: candidate.property,
        value: candidate.negative ? `calc(${v} * -1)` : v,
        important: candidate.important
      });
    }

    if (nodes.length === 0) return '';
    return serializeAST(nodes, candidate);
  }
}

function contextAwareSplit(str: string, delimiter: string): string[] {
  const result: string[] = [];
  let current = '';
  let depth = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str[i];
    if (char === '[') depth++;
    else if (char === ']') depth--;
    if (char === delimiter && depth === 0) {
      result.push(current);
      current = '';
    } else {
      current += char;
    }
  }
  if (current) result.push(current);
  return result;
}



function serializeAST(nodes: ASTNode[], candidate: Candidate): string {
  let declarations = "";
  const escapedName = candidate.raw.replace(/([\[\]/!:#.])/g, '\\$1');
  let selectorTarget = `.${escapedName}`;

  let wrapperStart = "";
  let wrapperEnd = "";
  
  // Apply our variant transformations
  for (const variant of candidate.variants) {
    // Media queries
    if (variant === 'sm') { wrapperStart += '@media (min-width: 40rem) { '; wrapperEnd = ' }' + wrapperEnd; continue; }
    if (variant === 'md') { wrapperStart += '@media (min-width: 48rem) { '; wrapperEnd = ' }' + wrapperEnd; continue; }
    if (variant === 'lg') { wrapperStart += '@media (min-width: 64rem) { '; wrapperEnd = ' }' + wrapperEnd; continue; }
    if (variant === 'xl') { wrapperStart += '@media (min-width: 80rem) { '; wrapperEnd = ' }' + wrapperEnd; continue; }
    if (variant === '2xl') { wrapperStart += '@media (min-width: 96rem) { '; wrapperEnd = ' }' + wrapperEnd; continue; }
    if (variant === 'dark') { wrapperStart += '@media (prefers-color-scheme: dark) { '; wrapperEnd = ' }' + wrapperEnd; continue; }
    if (variant === 'print') { wrapperStart += '@media print { '; wrapperEnd = ' }' + wrapperEnd; continue; }
    
    // Group & Peer compound variants (simplified for native parity mapping)
    if (variant.startsWith('group-')) {
       const sub = variant.slice(6);
       selectorTarget = `.group:${sub === 'hover' ? 'hover' : sub === 'focus' ? 'focus' : sub} ${selectorTarget}`;
       continue;
    }
    if (variant.startsWith('peer-')) {
       const sub = variant.slice(5);
       selectorTarget = `.peer:${sub === 'hover' ? 'hover' : sub === 'focus' ? 'focus' : sub} ~ ${selectorTarget}`;
       continue;
    }
    
    // Arbitrary variants [&_p]:hover etc
    if (variant.startsWith('[') && variant.endsWith(']')) {
        const customSel = variant.slice(1, -1).replace(/_/g, ' ');
        if (customSel.includes('&')) {
            selectorTarget = customSel.replace(/&/g, selectorTarget);
        } else {
            wrapperStart += `@media ${customSel} { `; wrapperEnd = ' }' + wrapperEnd; 
        }
        continue;
    }
    
    // Map pseudos natively
    const pseudoMap: Record<string, string> = {
      first: ':first-child', last: ':last-child', even: ':nth-child(even)', odd: ':nth-child(odd)',
      hover: ':hover', focus: ':focus', 'focus-within': ':focus-within', 'focus-visible': ':focus-visible',
      active: ':active', disabled: ':disabled', checked: ':checked',
      'in-range': ':in-range', 'out-of-range': ':out-of-range',
      'placeholder-shown': ':placeholder-shown', autofill: ':autofill',
      'read-only': ':read-only', open: '[open]', empty: ':empty',
      target: ':target', 'first-of-type': ':first-of-type', 'last-of-type': ':last-of-type',
      'only-of-type': ':only-of-type', 'popover-open': ':popover-open',
      enabled: ':enabled', indeterminate: ':indeterminate', default: ':default',
      required: ':required', valid: ':valid', invalid: ':invalid'
    };
    
    if (pseudoMap[variant]) {
       selectorTarget += pseudoMap[variant];
    } else {
       // Passthrough valid custom state pseudos
       selectorTarget += `:${variant}`;
    }
  }
  
  // Deterministic Property Sort Order (Tailwind Parity)
  const PROPERTY_ORDER_MAP: Record<string, number> = {
    'appearance': 1, 'display': 2, 'position': 3, 'top': 4, 'right': 5, 'bottom': 6, 'left': 7, 'inset': 8,
    'flex': 10, 'flex-basis': 11, 'flex-direction': 12, 'flex-grow': 13, 'flex-shrink': 14, 'flex-wrap': 15,
    'grid': 20, 'grid-area': 21, 'gap': 25, 'align-content': 30, 'align-items': 31, 'align-self': 32,
    'justify-content': 35, 'justify-items': 36, 'justify-self': 37,
    'order': 40, 'float': 45, 'clear': 46,
    'width': 50, 'min-width': 51, 'max-width': 52, 'height': 53, 'min-height': 54, 'max-height': 55,
    'inline-size': 56, 'block-size': 57,
    'margin': 60, 'margin-top': 61, 'margin-right': 62, 'margin-bottom': 63, 'margin-left': 64,
    'padding': 70, 'padding-top': 71, 'padding-right': 72, 'padding-bottom': 73, 'padding-left': 74,
    'font-family': 80, 'font-size': 81, 'font-weight': 82, 'line-height': 83, 'letter-spacing': 84,
    'color': 90, 'text-align': 91, 'text-decoration': 92, 'text-transform': 93,
    'background': 100, 'background-color': 101, 'background-image': 102,
    'border': 110, 'border-width': 111, 'border-style': 112, 'border-color': 113, 'border-radius': 114,
    'outline': 120, 'outline-width': 121, 'outline-style': 122, 'outline-color': 123, 'outline-offset': 124,
    'opacity': 130, 'visibility': 131, 'z-index': 132, 'content': 133,
    'transition': 140, 'transition-property': 141, 'transition-duration': 142, 'transition-timing-function': 143,
    'transform': 150, 'animation': 151, 'filter': 152, 'backdrop-filter': 153
  };

  const sortedNodes = [...nodes].sort((a, b) => {
    if (a.kind !== 'declaration' || b.kind !== 'declaration') return 0;
    const propA = a.property || "";
    const propB = b.property || "";
    const orderA = PROPERTY_ORDER_MAP[propA] || 999;
    const orderB = PROPERTY_ORDER_MAP[propB] || 999;
    if (orderA !== orderB) return orderA - orderB;
    return propA.localeCompare(propB);
  });

  let extraCSS = "";
  for (const node of sortedNodes) {
    if (node.kind === 'declaration') {
      if (node.property === 'raw') {
        declarations += node.value;
      } else {
        declarations += `${node.property}: ${node.value}${node.important || candidate.important ? ' !important' : ''}; `;
      }
    } else if (node.kind === 'at-rule') {
      extraCSS += `@${node.name} ${node.params} { ${node.nodes ? node.nodes.map(n => `${n.property}: ${n.value};`).join(' ') : ''} } `;
    } else if (node.kind === 'at-root' && node.selector) {
      // Direct nested rule injection with '&' resolution
      const fullSelector = node.selector.includes('&') 
        ? node.selector.replace(/&/g, selectorTarget)
        : `${selectorTarget} ${node.selector}`;
      const body = node.nodes?.map(n => n.property === 'raw' ? n.value : `${n.property}: ${n.value};`).join('') || '';
      declarations += `} ${fullSelector} { ${body} `;
    }
  }
  
  if (!declarations && !extraCSS) return "";
  return `${extraCSS}${wrapperStart}${selectorTarget} { ${declarations}}${wrapperEnd}`;
}




// ============================================================================
// 3. UTILITY REGISTRY
// ============================================================================
/**
 * tailwind-utilities.ts — Complete Tailwind v4 utility registry
 * Ported from @tailwindcss/browser@4.2.2
 * ZCZS: Pure registration functions, zero heap allocation at runtime
 */
// Helper: create a declaration node (borrowing pattern — no allocation beyond the literal)
function d(property: string, value: string, important = false): ASTNode {
  return { kind: 'declaration', property, value, important };
}

// Helper: create an at-root node
function K(nodes: ASTNode[]): ASTNode {
  return { kind: 'at-root', nodes };
}

// Helper: register a batch of static name→declarations
function statics(ds: DesignSystem, entries: [string, [string, string, boolean?][]][]) {
  for (const [name, decls] of entries) {
    ds.static(name, () => decls.map(([p, v, imp]) => d(p, v, imp)));
  }
}

// Helper: resolve spacing value from bare number or keyword
function resolveSpacing(val: string, negative = false): string {
  if (val === 'px') return negative ? '-1px' : '1px';
  if (val === 'auto') return 'auto';
  if (val === 'full') return negative ? '-100%' : '100%';
  if (val === 'screen') return '100vw';
  if (val.includes('var(')) return val;
  // Decimal support: 1.5 → calc(var(--spacing) * 1.5)
  const num = Number(val);
  if (!Number.isNaN(num)) {
    const expr = `calc(var(--spacing) * ${val})`;
    return negative ? `calc(${expr} * -1)` : expr;
  }
  return val;
}

function resolveThemeValue(key: string, v: string): string {
  if (v === 'none') return 'none';
  if (v.startsWith('[') || v.startsWith('#') || v.includes('(')) return v;
  // v4 convention: use theme variables for named keys
  return `var(--${key}-${v}, ${v})`;
}

// Helper: resolve color with optional opacity modifier
function resolveColor(val: string | ValueNode | undefined, modifier?: ValueNode | null): string {
  const v = (typeof val === 'string' ? val : val?.value) || '';
  if (v === 'transparent') return 'transparent';
  if (v === 'current') return 'currentcolor';
  if (v === 'inherit') return 'inherit';
  
  // v4 convention: if it starts with [ it is already resolved or arbitrary
  let color = v.startsWith('#') || v.includes('var(') || v.includes('(') || v.startsWith('[')
    ? v
    : `var(--color-${v})`;
    
  if (modifier) {
    const opacity = /^\d+$/.test(modifier.value) ? `${modifier.value}%` : modifier.value;
    return `color-mix(in oklch, ${color} ${opacity}, transparent)`;
  }
  return color;
}


// _STATIC_BOOT_MAP mirrors PACKED_STATIC_DICTIONARY split into individual
// 'class§prop:value' entries for registering statics into DesignSystem on boot.
let _STATIC_BOOT_MAP: string[] = [];

export function populateStandardUtilities(ds: DesignSystem): void {
  // Boot-time static keyword registration from PACKED_STATIC_DICTIONARY.
  // Replaces ~470 lines of explicit statics() calls.
  if (_STATIC_BOOT_MAP.length === 0) {
    _STATIC_BOOT_MAP = PACKED_STATIC_DICTIONARY.split("|");
  }
  for (const entry of _STATIC_BOOT_MAP) {
    const idx = entry.indexOf("§");
    if (idx === -1) continue;
    const name = entry.slice(0, idx);
    const decls = entry.slice(idx + 1).split(";").filter(Boolean).map((decl: string) => {
      const ci = decl.indexOf(":");
      return ci === -1 ? null : d(decl.slice(0, ci), decl.slice(ci + 1));
    }).filter(Boolean) as ASTNode[];
    ds.static(name, () => decls);
  }

  // Spacing
  const _sp: Record<string, string[]> = {
    m:["margin"],mx:["margin-inline"],my:["margin-block"],
    ms:["margin-inline-start"],me:["margin-inline-end"],
    mt:["margin-top"],mr:["margin-right"],mb:["margin-bottom"],ml:["margin-left"],
    p:["padding"],px:["padding-inline"],py:["padding-block"],
    ps:["padding-inline-start"],pe:["padding-inline-end"],
    pt:["padding-top"],pr:["padding-right"],pb:["padding-bottom"],pl:["padding-left"],
    gap:["gap"],"gap-x":["column-gap"],"gap-y":["row-gap"],
  };
  for (const [root, props] of Object.entries(_sp)) {
    if (root[0] === "m") ds.static(root + "-auto", () => props.map(p => d(p, "auto")));
    ds.functional(root, (c) => { if (!c.value) return; return props.map(p => d(p, resolveSpacing(c.value!.value, c.negative))); });
  }

  // Sizing
  const _sz: Record<string, string> = {
    w:"width",h:"height","min-w":"min-width","min-h":"min-height","max-w":"max-width","max-h":"max-height",
  };
  for (const [kw,val] of [["full","100%"],["min","min-content"],["max","max-content"],["fit","fit-content"]] as const) {
    for (const [r,p] of Object.entries(_sz)) ds.static(r+"-"+kw, () => [d(p,val)]);
    ds.static("size-"+kw, () => [d("width",val),d("height",val)]);
  }
  const _solveSz = (v: string, prop: string, neg: boolean): ASTNode[] => {
    if (v === "auto") return [d(prop,"auto")];
    if (v.includes("/")) { const [n,dn]=v.split("/"); if(n&&dn&&!isNaN(+n)&&!isNaN(+dn)) return [d(prop,`calc(${n}/${dn}*100%)`)]; }
    return [d(prop, resolveSpacing(v, neg))];
  };
  for (const [root,prop] of Object.entries(_sz)) {
    ds.functional(root, (c) => { if (!c.value) return; return _solveSz(c.value.value, prop, c.negative); });
  }
  ds.functional("size", (c) => {
    if (!c.value) return;
    return [..._solveSz(c.value.value,"width",c.negative), ..._solveSz(c.value.value,"height",c.negative)];
  });

  // Insets
  const _in: Record<string, string[]> = {
    inset:["inset"],"inset-x":["inset-inline"],"inset-y":["inset-block"],
    top:["top"],right:["right"],bottom:["bottom"],left:["left"],
  };
  for (const [root,props] of Object.entries(_in)) {
    ds.static(root+"-auto", () => props.map(p=>d(p,"auto")));
    ds.static(root+"-full", () => props.map(p=>d(p,"100%")));
    ds.functional(root, (c) => { if (!c.value) return; return props.map(p=>d(p,resolveSpacing(c.value!.value,c.negative))); });
  }

  // Colors
  for (const [root,prop] of [
    ["bg","background-color"],["border","border-color"],
    ["fill","fill"],["stroke","stroke"],["accent","accent-color"],["caret","caret-color"],
  ] as [string,string][]) {
    ds.functional(root, (c) => { if (!c.value) return; return [d(prop,resolveColor(c.value,c.modifier))]; });
  }
  const _textScale = new Set(["xs","sm","base","lg","xl","2xl","3xl","4xl","5xl","6xl","7xl","8xl","9xl"]);
  ds.functional("text", (c) => {
    if (!c.value) return;
    const v = c.value.value;
    if (_textScale.has(v) || /^\d/.test(v)) {
      return [d("font-size",`var(--text-${v})`),d("line-height",`var(--text-${v}--line-height,1.5)`)];
    }
    return [d("color",resolveColor(c.value,c.modifier))];
  });

  // Typography
  for (const f of ["sans","serif","mono"]) ds.static(`font-${f}`, () => [d("font-family",`var(--font-${f})`)]);
  const _fw: Record<string,string> = {thin:"100",extralight:"200",light:"300",normal:"400",medium:"500",semibold:"600",bold:"700",extrabold:"800",black:"900"};
  ds.functional("font", (c) => { if (!c.value) return; const v=c.value.value; if(["sans","serif","mono"].includes(v)) return; return [d("font-weight",_fw[v]||v)]; });
  const _lhMap: Record<string,string> = {none:"1",tight:"1.25",snug:"1.375",normal:"1.5",relaxed:"1.625",loose:"2"};
  ds.functional("leading", (c) => { if (!c.value) return; return [d("line-height",_lhMap[c.value.value]||resolveSpacing(c.value.value))]; });
  ds.functional("tracking", (c) => { if (!c.value) return; const v=c.value.value; return [d("letter-spacing",v.includes("var(")?v:`var(--tracking-${v},${v})`)]; });
  ds.functional("indent", (c) => { if (!c.value) return; return [d("text-indent",resolveSpacing(c.value.value,c.negative))]; });

  // Borders
  for (const [root,props] of Object.entries({
    border:["border-width"],"border-x":["border-inline-width"],"border-y":["border-block-width"],
    "border-t":["border-top-width"],"border-r":["border-right-width"],
    "border-b":["border-bottom-width"],"border-l":["border-left-width"],
  } as Record<string,string[]>)) {
    ds.functional(root, (c) => {
      if (!c.value) return;
      const v=c.value.value;
      if (c.value.kind==="color"||v.startsWith("#")||["transparent","current","inherit"].includes(v)) {
        return props.map(p=>d(p.replace("-width","-color"),resolveColor(c.value,c.modifier)));
      }
      return [...props.map(p=>d(p,/^\d+$/.test(v)?v+"px":v)),d("border-style","solid")];
    });
  }
  const _rad: Record<string,string[]> = {
    rounded:["border-radius"],
    "rounded-t":["border-top-left-radius","border-top-right-radius"],
    "rounded-r":["border-top-right-radius","border-bottom-right-radius"],
    "rounded-b":["border-bottom-right-radius","border-bottom-left-radius"],
    "rounded-l":["border-top-left-radius","border-bottom-left-radius"],
    "rounded-tl":["border-top-left-radius"],"rounded-tr":["border-top-right-radius"],
    "rounded-br":["border-bottom-right-radius"],"rounded-bl":["border-bottom-left-radius"],
  };
  for (const [root,props] of Object.entries(_rad)) {
    ds.static(root+"-none", () => props.map(p=>d(p,"0")));
    ds.static(root+"-full", () => props.map(p=>d(p,"calc(infinity * 1px)")));
    ds.functional(root, (c) => { if (!c.value) return; const v=c.value.value; return props.map(p=>d(p,v.includes("var(")?v:`var(--radius-${v},${v})`)); });
  }

  // Opacity
  ds.functional("opacity", (c) => { if (!c.value) return; const v=c.value.value,n=Number(v); return [d("opacity",!isNaN(n)&&n>=0&&n<=100?v+"%":v)]; });

  // Shadow / Ring
  const _sv="var(--tw-inset-shadow,0 0 #0000),var(--tw-inset-ring-shadow,0 0 #0000),var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow,0 0 #0000)";
  ds.functional("shadow", (c) => {
    if (!c.value) return [d("--tw-shadow","0 1px 3px 0 rgb(0 0 0/0.1),0 1px 2px -1px rgb(0 0 0/0.1)"),d("box-shadow",_sv)];
    const v=c.value.value;
    if (v==="none") return [d("box-shadow","none")];
    if (!["sm","md","lg","xl","2xl","inner"].includes(v)&&!/^\d/.test(v)) return [d("--tw-shadow-color",resolveColor(c.value,c.modifier)),d("box-shadow",_sv)];
    return [d("--tw-shadow",`var(--shadow-${v})`),d("box-shadow",_sv)];
  });
  ds.functional("ring", (c) => {
    if (!c.value) return [d("--tw-ring-shadow","var(--tw-ring-inset,) 0 0 0 calc(3px + var(--tw-ring-offset-width,0px)) var(--tw-ring-color,currentColor)"),d("box-shadow",_sv)];
    const v=c.value.value;
    if (!/^\d/.test(v)&&v!=="px") return [d("--tw-ring-color",resolveColor(c.value,c.modifier)),d("box-shadow",_sv)];
    const w=/^\d+$/.test(v)?v+"px":resolveSpacing(v);
    return [d("--tw-ring-shadow",`var(--tw-ring-inset,) 0 0 0 calc(${w} + var(--tw-ring-offset-width,0px)) var(--tw-ring-color,currentColor)`),d("box-shadow",_sv)];
  });

  // Transitions / Animation
  ds.functional("transition", (c) => {
    const v=c.value?.value;
    const prop=!v?"color,background-color,border-color,outline-color,text-decoration-color,fill,stroke,opacity,box-shadow,transform,translate,scale,rotate,filter,backdrop-filter"
      :v==="none"?"none":v==="all"?"all"
      :v==="colors"?"color,background-color,border-color,outline-color,text-decoration-color,fill,stroke"
      :v==="shadow"?"box-shadow":v==="transform"?"transform,translate,scale,rotate":v;
    return [d("transition-property",prop),d("transition-timing-function","var(--tw-ease,ease)"),d("transition-duration","var(--tw-duration,150ms)")];
  });
  ds.functional("duration", (c) => { if (!c.value) return; const v=/^\d+$/.test(c.value.value)?c.value.value+"ms":c.value.value; return [d("--tw-duration",v),d("transition-duration",v)]; });
  ds.functional("delay", (c) => { if (!c.value) return; const v=/^\d+$/.test(c.value.value)?c.value.value+"ms":c.value.value; return [d("transition-delay",v)]; });
  ds.functional("ease", (c) => { if (!c.value) return; return [d("--tw-ease",c.value.value),d("transition-timing-function",c.value.value)]; });
  ds.functional("animate", (c) => {
    if (!c.value) return;
    if (c.value.value==="none") return [d("animation","none")];
    const v=c.value.value;
    return [d("animation",v.startsWith("[")?v.slice(1,-1).replace(/_/g," "):`var(--animate-${v})`)];
  });

  // Z / Flex / Grid / Scroll / Misc
  ds.functional("z", (c) => { if (!c.value) return; const v=c.value.value; return v==="auto"?[d("z-index","auto")]:[d("z-index",c.negative?`calc(${v}*-1)`:v)]; });
  ds.functional("flex", (c) => {
    if (!c.value) return;
    const v=c.value.value;
    if (v.includes("/")) { const [n,dn]=v.split("/"); if(n&&dn&&!isNaN(+n)&&!isNaN(+dn)) return [d("flex",`calc(${n}/${dn}*100%)`)]; }
    if (/^\d+$/.test(v)) return [d("flex",`${v} ${v} 0%`)];
    return [d("flex",v)];
  });
  ds.functional("grow", (c) => [d("flex-grow",c.value?.value||"1")]);
  ds.functional("shrink", (c) => [d("flex-shrink",c.value?.value||"1")]);
  ds.functional("basis", (c) => {
    if (!c.value) return;
    const v=c.value.value;
    if (v==="auto") return [d("flex-basis","auto")];
    if (v==="full") return [d("flex-basis","100%")];
    if (v.includes("/")) { const [n,dn]=v.split("/"); if(n&&dn&&!isNaN(+n)&&!isNaN(+dn)) return [d("flex-basis",`calc(${n}/${dn}*100%)`)]; }
    return [d("flex-basis",resolveSpacing(v))];
  });
  ds.functional("order", (c) => { if (!c.value) return; const v=c.value.value; if(v==="first") return [d("order","-9999")]; if(v==="last") return [d("order","9999")]; return [d("order",c.negative?`calc(${v}*-1)`:v)]; });
  ds.functional("grid-cols", (c) => { if (!c.value) return; const v=c.value.value; if(v==="none") return [d("grid-template-columns","none")]; if(v==="subgrid") return [d("grid-template-columns","subgrid")]; if(/^\d+$/.test(v)) return [d("grid-template-columns",`repeat(${v},minmax(0,1fr))`)]; return [d("grid-template-columns",v)]; });
  ds.functional("grid-rows", (c) => { if (!c.value) return; const v=c.value.value; if(v==="none") return [d("grid-template-rows","none")]; if(v==="subgrid") return [d("grid-template-rows","subgrid")]; if(/^\d+$/.test(v)) return [d("grid-template-rows",`repeat(${v},minmax(0,1fr))`)]; return [d("grid-template-rows",v)]; });
  ds.functional("col-span", (c) => { if (!c.value) return; const v=c.value.value; return v==="full"?[d("grid-column","1/-1")]:[d("grid-column",`span ${v}/span ${v}`)]; });
  ds.functional("row-span", (c) => { if (!c.value) return; const v=c.value.value; return v==="full"?[d("grid-row","1/-1")]:[d("grid-row",`span ${v}/span ${v}`)]; });
  for (const [root,prop] of Object.entries({
    "scroll-m":"scroll-margin","scroll-mx":"scroll-margin-inline","scroll-my":"scroll-margin-block",
    "scroll-mt":"scroll-margin-top","scroll-mr":"scroll-margin-right","scroll-mb":"scroll-margin-bottom","scroll-ml":"scroll-margin-left",
    "scroll-p":"scroll-padding","scroll-px":"scroll-padding-inline","scroll-py":"scroll-padding-block",
    "scroll-pt":"scroll-padding-top","scroll-pr":"scroll-padding-right","scroll-pb":"scroll-padding-bottom","scroll-pl":"scroll-padding-left",
  } as Record<string,string>)) {
    ds.functional(root, (c) => { if (!c.value) return; return [d(prop,resolveSpacing(c.value.value,c.negative))]; });
  }
  ds.functional("aspect", (c) => { if (!c.value) return; const v=c.value.value; if(v==="auto") return [d("aspect-ratio","auto")]; if(v==="square") return [d("aspect-ratio","1/1")]; if(v==="video") return [d("aspect-ratio","16/9")]; return [d("aspect-ratio",v)]; });
  ds.functional("outline", (c) => {
    if (!c.value) return;
    const v=c.value.value;
    if (v==="none") return [d("outline","none")];
    if (c.value.kind==="color"||!/^\d/.test(v)) return [d("--tw-outline-color",resolveColor(c.value,c.modifier)),d("outline","var(--tw-outline-style,solid) var(--tw-outline-width,1px) var(--tw-outline-color,currentColor)")];
    return [d("--tw-outline-width",resolveSpacing(v)),d("outline","var(--tw-outline-style,solid) var(--tw-outline-width,1px) var(--tw-outline-color,currentColor)")];
  });
  ds.functional("bg-linear", (c) => { if (c.value?.kind==="named") return [{kind:"declaration",property:"background-image",value:`linear-gradient(${c.value.value},var(--tw-gradient-stops))`}]; });
  ds.functional("from", (c) => { if (c.value?.kind==="named") { const color=resolveColor(c.value,c.modifier); return [{kind:"declaration",property:"--tw-gradient-from",value:color},{kind:"declaration",property:"--tw-gradient-stops",value:"var(--tw-gradient-from),var(--tw-gradient-to,transparent)"}]; } });
}

// ═══════════════════════════════════════════════════════
// 25. COMPOSITING @PROPERTY REGISTRATIONS
// ═══════════════════════════════════════════════════════
const COMPOSITING_VARS = [
  { name: '--tw-blur', initial: ' ', syntax: '*' },
  { name: '--tw-brightness', initial: ' ', syntax: '*' },
  { name: '--tw-contrast', initial: ' ', syntax: '*' },
  { name: '--tw-grayscale', initial: ' ', syntax: '*' },
  { name: '--tw-hue-rotate', initial: ' ', syntax: '*' },
  { name: '--tw-invert', initial: ' ', syntax: '*' },
  { name: '--tw-saturate', initial: ' ', syntax: '*' },
  { name: '--tw-sepia', initial: ' ', syntax: '*' },
  { name: '--tw-drop-shadow', initial: ' ', syntax: '*' },
  { name: '--tw-backdrop-blur', initial: ' ', syntax: '*' },
  { name: '--tw-backdrop-brightness', initial: ' ', syntax: '*' },
  { name: '--tw-backdrop-contrast', initial: ' ', syntax: '*' },
  { name: '--tw-backdrop-grayscale', initial: ' ', syntax: '*' },
  { name: '--tw-backdrop-hue-rotate', initial: ' ', syntax: '*' },
  { name: '--tw-backdrop-invert', initial: ' ', syntax: '*' },
  { name: '--tw-backdrop-opacity', initial: ' ', syntax: '*' },
  { name: '--tw-backdrop-saturate', initial: ' ', syntax: '*' },
  { name: '--tw-backdrop-sepia', initial: ' ', syntax: '*' },
  { name: '--tw-scale-x', initial: '1', syntax: '<number>' },
  { name: '--tw-scale-y', initial: '1', syntax: '<number>' },
  { name: '--tw-scale-z', initial: '1', syntax: '<number>' },
  { name: '--tw-rotate-x', initial: '0deg', syntax: '<angle>' },
  { name: '--tw-rotate-y', initial: '0deg', syntax: '<angle>' },
  { name: '--tw-rotate-z', initial: '0deg', syntax: '<angle>' },
  { name: '--tw-translate-x', initial: '0', syntax: '*' },
  { name: '--tw-translate-y', initial: '0', syntax: '*' },
  { name: '--tw-translate-z', initial: '0', syntax: '*' },
  { name: '--tw-skew-x', initial: '0deg', syntax: '<angle>' },
  { name: '--tw-skew-y', initial: '0deg', syntax: '<angle>' },
  { name: '--tw-inset-shadow', initial: '0 0 #0000', syntax: '*' },
  { name: '--tw-inset-ring-shadow', initial: '0 0 #0000', syntax: '*' },
  { name: '--tw-ring-offset-shadow', initial: '0 0 #0000', syntax: '*' },
  { name: '--tw-ring-shadow', initial: '0 0 #0000', syntax: '*' },
  { name: '--tw-shadow', initial: '0 0 #0000', syntax: '*' },
  { name: '--tw-shadow-colored', initial: '0 0 #0000', syntax: '*' },
];

function registerCompositingProperties() {
  let css = '';
  for (const v of COMPOSITING_VARS) {
    css += `@property ${v.name} { syntax: "${v.syntax}"; inherits: false; initial-value: ${v.initial}; }\n`;
  }
  return css;
}


// ============================================================================
// 4. STYLESHEET MANAGER (DOM Injection)
// ============================================================================


class StyleSheetManager {
  private _adoptedSheets: Map<string, CSSStyleSheet> = new Map();
  private _jitSheet: CSSStyleSheet | null = null;
  private _knownClasses: Set<string> = new Set();
  private _nextId = 0;
  private _preflightEmitted = false;

  private _getJitSheet(): CSSStyleSheet {
    if (!this._jitSheet) {
      if ('CSSStyleSheet' in globalThis) {
        this._jitSheet = new CSSStyleSheet();
        if ('document' in globalThis) {
          document.adoptedStyleSheets = [...document.adoptedStyleSheets, this._jitSheet];
        }
      } else {
        // Fallback for extremely niche environments if necessary, but Nexus-UX mandates modern APIs
        throw new Error("Nexus-UX: CSSStyleSheet (AdoptedStyleSheets) is required for JIT.");
      }
    }
    return this._jitSheet;
  }

  /**
   * Initializes the JIT engine and starts the passive style scanner.
   * Scans existing DOM and watches for new classes to eliminate FOUC.
   */
  public emitPreflightAndTheme(): void {
    if (typeof document === 'undefined') return;

    // Native Style Firewall: abort if external styling branch (Tailwind PlayCDN)
    if (document.querySelector('[data-ignore\\:style]')) {
      return;
    }

    if (this._preflightEmitted) return;
    
    // 1. Base browser resets (Tailwind v4 preflight — AOT injected from jsDelivr CDN)
    if (PACKED_PREFLIGHT.length > 0) {
      this.adoptCSSSync(PACKED_PREFLIGHT, 'nexus-preflight');
    }

    // 2. Framework component overrides (sortable/drag-drop classes)
    if (PACKED_COMPONENTS.length > 0) {
      this.adoptCSSSync(PACKED_COMPONENTS, 'nexus-components');
    }

    // 3. Animation keyframes
    if (PACKED_KEYFRAMES.length > 0) {
      this.adoptCSSSync(PACKED_KEYFRAMES, 'nexus-keyframes');
    }

    // 4. Theme design tokens + runtime compositing
    const compositingCSS = registerCompositingProperties();
    const themeBlock = PACKED_THEME.length > 0 ? PACKED_THEME + compositingCSS : compositingCSS;
    if (themeBlock.length > 0) {
      this.adoptCSSSync(themeBlock, 'nexus-theme');
    }

    this._preflightEmitted = true;

    // Passive Style Scanner: Synchronously scan existing DOM to adopt classes.
    // This kills FOUC by ensuring styles are registered before the first paint 
    // for all elements already in the buffer during initial boot.
    // Continuous scanning is now handled by the main framework MutationObserver.
    const all = document.querySelectorAll('*');
    all.forEach(el => {
      if (el instanceof HTMLElement) {
        el.classList.forEach(cls => this.adoptClass(cls, el));
      }
    });
  }

  /**
   * Synchronous adoption for immediate framework boot.
   */
  adoptCSSSync(cssText: string, id?: string): () => void {
    const sheetId = id || `_auto_${this._nextId++}`;
    const existing = this._adoptedSheets.get(sheetId);
    
    if (existing) {
      existing.replaceSync(cssText);
      return () => this.removeSheet(sheetId);
    }

    if (typeof CSSStyleSheet === 'undefined') return () => {};

    const sheet = new CSSStyleSheet();
    sheet.replaceSync(cssText);
    this._adoptedSheets.set(sheetId, sheet);
    
    if ('document' in globalThis) {
      document.adoptedStyleSheets = [...document.adoptedStyleSheets, sheet];
    }
    return () => this.removeSheet(sheetId);
  }

  async adoptCSS(cssText: string, id?: string): Promise<() => void> {
    // 1. Tailwind v4 At-Rule Intersection (Play CDN Parity)
    const processedCSS = this.processAtRules(cssText);
    
    const sheetId = id || `_auto_${this._nextId++}`;
    const existing = this._adoptedSheets.get(sheetId);
    if (existing) {
      await existing.replace(processedCSS);
      return () => this.removeSheet(sheetId);
    }

    if (typeof CSSStyleSheet === 'undefined') return () => {};

    const sheet = new CSSStyleSheet();
    await sheet.replace(processedCSS);
    this._adoptedSheets.set(sheetId, sheet);
    if ('document' in globalThis) {
      document.adoptedStyleSheets = [...document.adoptedStyleSheets, sheet];
    }
    return () => this.removeSheet(sheetId);
  }

  /**
   * Scans and interprets Tailwind v4 at-rules.
   * Internal logic for achieveing 100% Play CDN functional parity.
   */
  private processAtRules(css: string): string {
    let result = css;

    // A. @theme parsing (Handle multiple blocks)
    const themeRegex = /@theme\s*(?:default|inline|reference)?\s*\{([\s\S]*?)\}/g;
    let themeMatch;
    while ((themeMatch = themeRegex.exec(css)) !== null) {
      const themeInternal = themeMatch[1];
      const varRegex = /(--[\w-]+)\s*:\s*([^;]+);/g;
      let m;
      while ((m = varRegex.exec(themeInternal)) !== null) {
        const [_, key, _val] = m;
        if (key.startsWith('--color-')) {
          const colorName = key.replace('--color-', '');
          designSystem.functional(colorName, (c) => {
            const propertyMap: Record<string, string> = { bg: 'background-color', text: 'color', border: 'border-color', fill: 'fill', stroke: 'stroke' };
            const prop = propertyMap[c.root] || c.root;
            const color = resolveColor(key, c.modifier);
            return [{ kind: 'declaration', property: prop, value: color }];
          });
        }
      }
    }

    // B. @utility parsing (Tailwind v4 syntax)
    const utilityRegex = /@utility\s+([\w-]+)\s*\{([\s\S]*?)\}/g;
    result = result.replace(utilityRegex, (_, root, body) => {
      designSystem.registerCustomRule(root, body);
      return '';
    });

    // C. @layer parsing (Robust component scanning for DaisyUI)
    const layerRegex = /@layer\s+([\w-]+)\s*\{([\s\S]*?)\}(?!\s*\{)/g;
    result = result.replace(layerRegex, (match, layerName, body) => {
       if (layerName === 'components') {
          // Robust scanning for class-based components (including complex selectors)
          const classDefRegex = /\.([\w-]+)[^{]*\{([\s\S]*?)\}/g;
          let cm;
          while ((cm = classDefRegex.exec(body)) !== null) {
             designSystem.registerCustomRule(cm[1], cm[2]);
          }
          return ''; // Strip components layer, handled by JIT
       }
       return match; // Keep base/utilities as pure CSS
    });

    return result;
  }

  adoptClass(className: string, el?: HTMLElement, runtime?: RuntimeContext): void {
    if (!className || className.trim() === '') return;

    // ZCZS Requirement: Native Style Firewall
    // If the element belongs to an isolated external styling branch, completely 
    // abort JIT evaluation to prevent compilation conflicts.
    if (el && el.closest && el.closest('[data-ignore\\:style]')) {
      return;
    }

    if (this._knownClasses.has(className)) return;

    try {
      this._knownClasses.add(className);
      const candidates = Array.from(designSystem.parseCandidate(className));
      for (const candidate of candidates) {
        const cssRules = designSystem.generateCSS(candidate);
        if (cssRules) {
          const sheet = this._getJitSheet();
          // Split by rules (Tailwind v4 JIT generates multiple rules for container queries/space-y)
          // Simple split by the closing brace followed by space/newline
          const rules = cssRules.split(/(?<=\})\s*(?=\.)|(?<=\})\s*(?=@)/g);
          for (const rule of rules) {
            if (rule.trim()) {
              try {
                sheet.insertRule(rule.trim(), sheet.cssRules.length);
              } catch (e) {
                // Ignore individual rule failures (e.g. invalid experimental selectors)
                console.debug(`Nexus-UX: Non-critical JIT insertion failure:`, e);
              }
            }
          }

          if (candidate.hasSignal && el && runtime) {
            this.adoptSignalBinding(el, candidate.hasSignal, runtime);
          }
        }
      }
    } catch (err) {
      console.warn(`Nexus-UX: Failed to JIT compile class "${className}":`, err);
    }
  }

  adoptSignalBinding(el: HTMLElement, signalName: string, runtime: RuntimeContext) {
    if (!el.hasAttribute('data-class')) {
       const currentBindings = (el as HTMLElement & { _signalBindings?: string[] })._signalBindings || [];
       if (!currentBindings.includes(signalName)) {
           currentBindings.push(signalName);
           (el as HTMLElement & { _signalBindings?: string[] })._signalBindings = currentBindings;
           
           const varName = signalName.replace(/[#.]/g, '-');
           runtime.effect(() => {
              const val = runtime.evaluate(el, signalName);
              el.style.setProperty(`--nx-${varName}`, String(val !== undefined ? val : ''));
           });
       }
    }
  }

  ensureRule(className: string, cssText: string): void {
    if (this._knownClasses.has(className)) return;
    const sheet = this._getJitSheet();
    try {
      sheet.insertRule(cssText, sheet.cssRules.length);
      this._knownClasses.add(className);
    } catch (_e) {
      /* ignore */
    }
  }

  collectRules(): string {
    const sheets: string[] = [];
    this._adoptedSheets.forEach((sheet) => {
      const rules: string[] = [];
      try {
        for (const rule of sheet.cssRules) rules.push(rule.cssText);
      } catch (_e) {
      /* ignore */
    }
      if (rules.length) sheets.push(rules.join('\n'));
    });

    if (this._jitSheet) {
      const rules: string[] = [];
      try {
        for (const rule of this._jitSheet.cssRules) rules.push(rule.cssText);
      } catch (_e) {
      /* ignore */
    }
      if (rules.length) sheets.push(rules.join('\n'));
    }
    return sheets.join('\n\n');
  }

  removeSheet(id: string): void {
    const sheet = this._adoptedSheets.get(id);
    if (!sheet) return;
    if ('document' in globalThis) {
      document.adoptedStyleSheets = document.adoptedStyleSheets.filter(s => s !== sheet);
    }
    this._adoptedSheets.delete(id);
  }

  dispose(): void {
    this._adoptedSheets.forEach((_sheet, id) => this.removeSheet(id));
    this._adoptedSheets.clear();
    if (this._jitSheet && 'document' in globalThis) {
      document.adoptedStyleSheets = document.adoptedStyleSheets.filter(s => s !== this._jitSheet);
      this._jitSheet = null;
    }
    this._knownClasses.clear();
    this._nextId = 0;
  }
}




// ============================================================================
// 5. INITIALIZATION & EXPORTS
// ============================================================================

export const designSystem = new DesignSystem();


export function populateStandardVariants(ds: DesignSystem) {
  // ═══════════════════════════════════════════════════════
  // PHASE 2 ADDITIONS (48 MISSING VARIANTS)
  // ═══════════════════════════════════════════════════════

  // 2A. Pseudo-classes
  const pseudos = [
    'enabled', 'indeterminate', 'default', 'required', 'valid', 'invalid',
    'in-range', 'out-of-range', 'placeholder-shown', 'autofill', 'read-only',
    'open', 'empty', 'target', 'even', 'odd', 'first', 'last', 'only',
    'first-of-type', 'last-of-type', 'only-of-type', 'popover-open', 'inert',
    'starting'
  ];
  
  pseudos.forEach(p => ds.variant(p, (_c) => [])); // The serializeAST handles pseudo generation for static variants
  
  // NOTE: Our JIT engine serialization handles mapping these strings to actual pseudo-selectors. 
  // We just need to register them so the parser doesn't reject them as invalid.

  // 2B. Parametric Variants
  const parametric = ['nth', 'nth-of-type', 'nth-last-of-type', 'has', 'not', 'is', 'where'];
  parametric.forEach(p => {
    ds.functional(p, (_c) => []); // Registered as functional roots but in variant context
  });

  // 2D. Accessibility
  ds.variant('contrast-more', (_c) => []); 
  ds.variant('contrast-less', (_c) => []);
  ds.variant('forced-colors', (_c) => []);

  // 2E. Misc
  ds.variant('file', (_c) => []);
  ds.variant('backdrop', (_c) => []);
  ds.variant('screen', (_c) => []);
  ds.variant('any', (_c) => []);
  ds.variant('aria', (_c) => []);
  ds.variant('data', (_c) => []);
  ds.variant('supports', (_c) => []);
  ds.variant('container', (_c) => []);
  ds.variant('min', (_c) => []);
  ds.variant('max', (_c) => []);
  
  // Update: 'group' and 'peer' compound variants
  ds.variant('group', (_c) => []);
  ds.variant('peer', (_c) => []);
}

export const stylesheet = new StyleSheetManager();



// ============================================================================
// 6. PACKED HYBRID JIT SUBSYSTEM
// ============================================================================
// Additions only — the DesignSystem compiler, StyleSheetManager, and all
// populateStandardUtilities() registrations above are completely untouched.

// Two-Tier Isolated Constructable StyleSheets
// preflightSheet: sealed once at boot via replaceSync() — never mutated again.
// jitSheet: live mutable layer for all runtime insertRule() / deleteRule() passes.
export const preflightSheet = typeof CSSStyleSheet !== 'undefined' ? new CSSStyleSheet() : { replaceSync() {} } as any;
export const jitSheet = typeof CSSStyleSheet !== 'undefined' ? new CSSStyleSheet() : { insertRule() {}, deleteRule() {}, cssRules: [] } as any;

if (typeof document !== 'undefined' && typeof CSSStyleSheet !== 'undefined') {
  document.adoptedStyleSheets = [...document.adoptedStyleSheets, preflightSheet, jitSheet];
}

// Internal state
const _ruleCache = new Set<string>();
let _isJitEngineBooted = false;
let _staticLookupMap = new Map<string, string>();

/**
 * 1. Packed Preflight Payload Placeholder
 * Automatically overwritten by compileStyleLayerPrimitives() in scripts/build.ts at AOT time.
 * Holds clean modern browser resets sourced from Tailwind v4 base layer.
 */


/**
 * 2. Algorithmic Packed Utility Dictionary String
 * Non-calculable static keyword classes compressed into a single opaque string.
 * Uses '§' as the key/value delimiter to safely bypass interior CSS colon characters.
 * Uses '|' as the entry separator.
 * Format: "className§property:value|className§property:value"
 */
const PACKED_STATIC_DICTIONARY =
  "flex§display:flex" +
  "|inline-flex§display:inline-flex" +
  "|grid§display:grid" +
  "|inline-grid§display:inline-grid" +
  "|block§display:block" +
  "|inline-block§display:inline-block" +
  "|inline§display:inline" +
  "|hidden§display:none" +
  "|contents§display:contents" +
  "|flow-root§display:flow-root" +
  "|list-item§display:list-item" +
  "|table§display:table" +
  "|table-caption§display:table-caption" +
  "|table-cell§display:table-cell" +
  "|table-column§display:table-column" +
  "|table-row§display:table-row" +
  "|static§position:static" +
  "|fixed§position:fixed" +
  "|absolute§position:absolute" +
  "|relative§position:relative" +
  "|sticky§position:sticky" +
  "|visible§visibility:visible" +
  "|invisible§visibility:hidden" +
  "|collapse§visibility:collapse" +
  "|isolate§isolation:isolate" +
  "|isolation-auto§isolation:auto" +
  "|flex-row§flex-direction:row" +
  "|flex-row-reverse§flex-direction:row-reverse" +
  "|flex-col§flex-direction:column" +
  "|flex-col-reverse§flex-direction:column-reverse" +
  "|flex-wrap§flex-wrap:wrap" +
  "|flex-nowrap§flex-wrap:nowrap" +
  "|flex-wrap-reverse§flex-wrap:wrap-reverse" +
  "|flex-auto§flex:auto" +
  "|flex-initial§flex:0 auto" +
  "|flex-none§flex:none" +
  "|grow§flex-grow:1" +
  "|shrink§flex-shrink:1" +
  "|items-start§align-items:flex-start" +
  "|items-end§align-items:flex-end" +
  "|items-center§align-items:center" +
  "|items-baseline§align-items:baseline" +
  "|items-stretch§align-items:stretch" +
  "|justify-start§justify-content:flex-start" +
  "|justify-end§justify-content:flex-end" +
  "|justify-center§justify-content:center" +
  "|justify-between§justify-content:space-between" +
  "|justify-around§justify-content:space-around" +
  "|justify-evenly§justify-content:space-evenly" +
  "|justify-stretch§justify-content:stretch" +
  "|content-start§align-content:flex-start" +
  "|content-end§align-content:flex-end" +
  "|content-center§align-content:center" +
  "|content-between§align-content:space-between" +
  "|content-around§align-content:space-around" +
  "|content-evenly§align-content:space-evenly" +
  "|content-stretch§align-content:stretch" +
  "|self-auto§align-self:auto" +
  "|self-start§align-self:flex-start" +
  "|self-end§align-self:flex-end" +
  "|self-center§align-self:center" +
  "|self-stretch§align-self:stretch" +
  "|self-baseline§align-self:baseline" +
  "|float-start§float:inline-start" +
  "|float-end§float:inline-end" +
  "|float-left§float:left" +
  "|float-right§float:right" +
  "|float-none§float:none" +
  "|clear-start§clear:inline-start" +
  "|clear-end§clear:inline-end" +
  "|clear-left§clear:left" +
  "|clear-right§clear:right" +
  "|clear-both§clear:both" +
  "|clear-none§clear:none" +
  "|overflow-auto§overflow:auto" +
  "|overflow-hidden§overflow:hidden" +
  "|overflow-clip§overflow:clip" +
  "|overflow-visible§overflow:visible" +
  "|overflow-scroll§overflow:scroll" +
  "|overflow-x-auto§overflow-x:auto" +
  "|overflow-x-hidden§overflow-x:hidden" +
  "|overflow-x-scroll§overflow-x:scroll" +
  "|overflow-y-auto§overflow-y:auto" +
  "|overflow-y-hidden§overflow-y:hidden" +
  "|overflow-y-scroll§overflow-y:scroll" +
  "|truncate§overflow:hidden" +
  "|whitespace-normal§white-space:normal" +
  "|whitespace-nowrap§white-space:nowrap" +
  "|whitespace-pre§white-space:pre" +
  "|whitespace-pre-line§white-space:pre-line" +
  "|whitespace-pre-wrap§white-space:pre-wrap" +
  "|whitespace-break-spaces§white-space:break-spaces" +
  "|break-normal§overflow-wrap:normal" +
  "|break-words§overflow-wrap:break-word" +
  "|break-all§word-break:break-all" +
  "|break-keep§word-break:keep-all" +
  "|antialiased§-webkit-font-smoothing:antialiased" +
  "|subpixel-antialiased§-webkit-font-smoothing:auto" +
  "|italic§font-style:italic" +
  "|not-italic§font-style:normal" +
  "|normal-nums§font-variant-numeric:normal" +
  "|uppercase§text-transform:uppercase" +
  "|lowercase§text-transform:lowercase" +
  "|capitalize§text-transform:capitalize" +
  "|normal-case§text-transform:none" +
  "|underline§text-decoration-line:underline" +
  "|overline§text-decoration-line:overline" +
  "|line-through§text-decoration-line:line-through" +
  "|no-underline§text-decoration-line:none" +
  "|text-left§text-align:left" +
  "|text-center§text-align:center" +
  "|text-right§text-align:right" +
  "|text-justify§text-align:justify" +
  "|text-start§text-align:start" +
  "|text-end§text-align:end" +
  "|align-baseline§vertical-align:baseline" +
  "|align-top§vertical-align:top" +
  "|align-middle§vertical-align:middle" +
  "|align-bottom§vertical-align:bottom" +
  "|align-text-top§vertical-align:text-top" +
  "|align-text-bottom§vertical-align:text-bottom" +
  "|align-sub§vertical-align:sub" +
  "|align-super§vertical-align:super" +
  "|bg-fixed§background-attachment:fixed" +
  "|bg-local§background-attachment:local" +
  "|bg-scroll§background-attachment:scroll" +
  "|bg-clip-border§background-clip:border-box" +
  "|bg-clip-padding§background-clip:padding-box" +
  "|bg-clip-content§background-clip:content-box" +
  "|bg-clip-text§background-clip:text" +
  "|bg-repeat§background-repeat:repeat" +
  "|bg-no-repeat§background-repeat:no-repeat" +
  "|bg-repeat-x§background-repeat:repeat-x" +
  "|bg-repeat-y§background-repeat:repeat-y" +
  "|bg-repeat-round§background-repeat:round" +
  "|bg-repeat-space§background-repeat:space" +
  "|bg-none§background-image:none" +
  "|border-solid§border-style:solid" +
  "|border-dashed§border-style:dashed" +
  "|border-dotted§border-style:dotted" +
  "|border-double§border-style:double" +
  "|border-hidden§border-style:hidden" +
  "|border-none§border-style:none" +
  "|divide-solid§border-style:solid" +
  "|divide-dashed§border-style:dashed" +
  "|divide-dotted§border-style:dotted" +
  "|divide-double§border-style:double" +
  "|divide-none§border-style:none" +
  "|outline-none§outline:2px solid transparent" +
  "|outline-dashed§outline-style:dashed" +
  "|outline-dotted§outline-style:dotted" +
  "|outline-double§outline-style:double" +
  "|outline-solid§outline-style:solid" +
  "|pointer-events-none§pointer-events:none" +
  "|pointer-events-auto§pointer-events:auto" +
  "|cursor-auto§cursor:auto" +
  "|cursor-default§cursor:default" +
  "|cursor-pointer§cursor:pointer" +
  "|cursor-wait§cursor:wait" +
  "|cursor-text§cursor:text" +
  "|cursor-move§cursor:move" +
  "|cursor-help§cursor:help" +
  "|cursor-not-allowed§cursor:not-allowed" +
  "|cursor-none§cursor:none" +
  "|cursor-grab§cursor:grab" +
  "|cursor-grabbing§cursor:grabbing" +
  "|select-none§user-select:none" +
  "|select-text§user-select:text" +
  "|select-all§user-select:all" +
  "|select-auto§user-select:auto" +
  "|resize-none§resize:none" +
  "|resize§resize:both" +
  "|resize-y§resize:vertical" +
  "|resize-x§resize:horizontal" +
  "|appearance-none§appearance:none" +
  "|appearance-auto§appearance:auto" +
  "|will-change-auto§will-change:auto" +
  "|will-change-scroll§will-change:scroll-position" +
  "|will-change-contents§will-change:contents" +
  "|will-change-transform§will-change:transform" +
  "|object-contain§object-fit:contain" +
  "|object-cover§object-fit:cover" +
  "|object-fill§object-fit:fill" +
  "|object-none§object-fit:none" +
  "|object-scale-down§object-fit:scale-down" +
  "|list-none§list-style-type:none" +
  "|list-disc§list-style-type:disc" +
  "|list-decimal§list-style-type:decimal" +
  "|sr-only§position:absolute" +
  "|not-sr-only§position:static" +
  "|touch-auto§touch-action:auto" +
  "|touch-none§touch-action:none" +
  "|touch-pan-x§touch-action:pan-x" +
  "|touch-pan-y§touch-action:pan-y" +
  "|touch-manipulation§touch-action:manipulation";

/**
 * Framework Initialization Bootstrap Hook
 * Call once at framework startup before the MutationObserver activates.
 * Idempotency-gated — safe to call multiple times (e.g. under hot-reload).
 */
export function initializeJitEngine(): void {
  if (_isJitEngineBooted) return;
  _isJitEngineBooted = true;

  // A. Seal preflight base resets into the isolated preflightSheet via replaceSync.
  //    This sheet is never mutated again after this point.
  preflightSheet.replaceSync(PACKED_PREFLIGHT);

  // B. Procedural spacing scale generation.
  //    Provisions --spacing-1 through --spacing-64 matching Tailwind v4 constraints.
  let spacingBlock = ':root { --spacing: 0.25rem; ';
  for (let i = 1; i <= 64; i++) {
    spacingBlock += `--spacing-${i}: calc(var(--spacing) * ${i});`;
  }
  spacingBlock += ' }';
  jitSheet.insertRule(spacingBlock, jitSheet.cssRules.length);

  // C. Hydrate static keyword map from the packed dictionary string.
  //    Splits on '|' for entries, '§' for key/value — never splits on ':'.
  const entries = PACKED_STATIC_DICTIONARY.split('|');
  for (let i = 0; i < entries.length; i++) {
    const delimIdx = entries[i].indexOf('§');
    if (delimIdx !== -1) {
      _staticLookupMap.set(entries[i].slice(0, delimIdx), entries[i].slice(delimIdx + 1));
    }
  }
}

/**
 * Core JIT Token Evaluator — Dual-Lane Processing
 *
 * Lane 1 (Procedural Mapper): Numeric, fractional, and directional utilities.
 *   Matches patterns like w-4, h-1/2, p-8, m-auto, gap-6 and computes CSS math.
 *   Zero dictionary lookup overhead.
 *
 * Lane 2 (Dictionary Unpacker): Non-calculable keyword classes.
 *   Performs an O(1) Map lookup into the hydrated _staticLookupMap.
 *
 * Variant prefixes (sm:, hover:, dark:, group-hover:) are stripped before
 * lane matching and re-applied as a CSS selector/media-query wrapper.
 *
 * Results are deduplicated via _ruleCache and injected into jitSheet.
 */
export function parseAndInjectToken(element: HTMLElement, rawToken: string): void {
  // Strip variant chain and isolate the utility token
  const colonParts = rawToken.split(':');
  const utilityToken = colonParts[colonParts.length - 1];
  const variants = colonParts.slice(0, -1);

  const safeClassName = rawToken.replace(/[:/[\].]/g, '_');

  // Deduplicate: class already compiled and injected
  if (_ruleCache.has(safeClassName)) {
    if (!element.classList.contains(safeClassName)) element.classList.add(safeClassName);
    return;
  }

  let cssValue = '';
  let cssProperty = '';

  // ── LANE 1: Procedural Variable Mapper ────────────────────────────────────
  // Handles: w-4, h-1/2, p-8, m-auto, gap-6, mt-2, px-4, py-3, etc.
  const proceduralMatch = utilityToken.match(
    /^(w|h|m|mt|mr|mb|ml|mx|my|p|pt|pr|pb|pl|px|py|gap|gap-x|gap-y|inset|top|right|bottom|left|min-w|max-w|min-h|max-h|basis|size)-(.+)$/
  );

  if (proceduralMatch) {
    const [, prefix, rawVal] = proceduralMatch;
    const propertyMap: Record<string, string> = {
      w: 'width', h: 'height',
      m: 'margin', mt: 'margin-top', mr: 'margin-right', mb: 'margin-bottom', ml: 'margin-left',
      mx: 'margin-inline', my: 'margin-block',
      p: 'padding', pt: 'padding-top', pr: 'padding-right', pb: 'padding-bottom', pl: 'padding-left',
      px: 'padding-inline', py: 'padding-block',
      gap: 'gap', 'gap-x': 'column-gap', 'gap-y': 'row-gap',
      inset: 'inset', top: 'top', right: 'right', bottom: 'bottom', left: 'left',
      'min-w': 'min-width', 'max-w': 'max-width',
      'min-h': 'min-height', 'max-h': 'max-height',
      basis: 'flex-basis', size: 'width'
    };
    cssProperty = propertyMap[prefix] || '';

    if (cssProperty) {
      if (rawVal === 'auto') {
        cssValue = 'auto';
      } else if (rawVal === 'full') {
        cssValue = '100%';
      } else if (rawVal === 'screen') {
        cssValue = prefix === 'w' || prefix === 'min-w' || prefix === 'max-w' ? '100vw' : '100vh';
      } else if (rawVal === 'px') {
        cssValue = '1px';
      } else if (rawVal === 'fit') {
        cssValue = 'fit-content';
      } else if (rawVal.includes('/')) {
        // Fractional: w-1/2 → 50%, w-3/4 → 75%
        const [num, den] = rawVal.split('/').map(Number);
        if (!isNaN(num) && !isNaN(den) && den !== 0) {
          cssValue = `${(num / den) * 100}%`;
        }
      } else if (!isNaN(Number(rawVal))) {
        cssValue = `calc(var(--spacing) * ${rawVal})`;
      }

      // If prefix 'size', also set height
      if (prefix === 'size' && cssValue) {
        const doubleRule = `.${safeClassName}{width:${cssValue};height:${cssValue};}`;
        _injectVariantWrapped(safeClassName, doubleRule, variants);
        _ruleCache.add(safeClassName);
        element.classList.add(safeClassName);
        return;
      }
    }
  }

  // ── LANE 2: Dictionary Unpacker ────────────────────────────────────────────
  if (!cssValue && _staticLookupMap.has(utilityToken)) {
    const declaration = _staticLookupMap.get(utilityToken)!;
    const colonIdx = declaration.indexOf(':');
    cssProperty = declaration.slice(0, colonIdx);
    cssValue = declaration.slice(colonIdx + 1);
  }

  if (cssProperty && cssValue) {
    const rule = `.${safeClassName}{${cssProperty}:${cssValue};}`;
    _injectVariantWrapped(safeClassName, rule, variants);
    _ruleCache.add(safeClassName);
    element.classList.add(safeClassName);
  }
}

/**
 * Wraps a compiled CSS rule string with variant media-query / pseudo-selector context
 * and inserts it into the mutable jitSheet layer.
 */
function _injectVariantWrapped(safeClassName: string, baseRule: string, variants: string[]): void {
  if (variants.length === 0) {
    jitSheet.insertRule(baseRule, jitSheet.cssRules.length);
    return;
  }

  const breakpointMap: Record<string, string> = {
    sm: '40rem', md: '48rem', lg: '64rem', xl: '80rem', '2xl': '96rem'
  };

  let wrappedRule = baseRule;

  // Apply variants in reverse order (innermost first)
  for (let i = variants.length - 1; i >= 0; i--) {
    const v = variants[i];
    if (breakpointMap[v]) {
      wrappedRule = `@media (min-width: ${breakpointMap[v]}) { ${wrappedRule} }`;
    } else if (v === 'dark') {
      wrappedRule = `@media (prefers-color-scheme: dark) { ${wrappedRule} }`;
    } else if (v === 'print') {
      wrappedRule = `@media print { ${wrappedRule} }`;
    } else if (v === 'hover') {
      wrappedRule = wrappedRule.replace(`.${safeClassName}`, `.${safeClassName}:hover`);
    } else if (v === 'focus') {
      wrappedRule = wrappedRule.replace(`.${safeClassName}`, `.${safeClassName}:focus`);
    } else if (v === 'active') {
      wrappedRule = wrappedRule.replace(`.${safeClassName}`, `.${safeClassName}:active`);
    } else if (v === 'disabled') {
      wrappedRule = wrappedRule.replace(`.${safeClassName}`, `.${safeClassName}:disabled`);
    } else if (v === 'focus-within') {
      wrappedRule = wrappedRule.replace(`.${safeClassName}`, `.${safeClassName}:focus-within`);
    } else if (v === 'focus-visible') {
      wrappedRule = wrappedRule.replace(`.${safeClassName}`, `.${safeClassName}:focus-visible`);
    } else if (v.startsWith('group-')) {
      const sub = v.slice(6);
      wrappedRule = wrappedRule.replace(`.${safeClassName}`, `.group:${sub} .${safeClassName}`);
    } else if (v.startsWith('peer-')) {
      const sub = v.slice(5);
      wrappedRule = wrappedRule.replace(`.${safeClassName}`, `.peer:${sub} ~ .${safeClassName}`);
    }
  }

  try {
    jitSheet.insertRule(wrappedRule, jitSheet.cssRules.length);
  } catch (_e) {
    // Non-critical — fallback for complex media+pseudo combos unsupported by insertRule
  }
}

/**
 * High-Performance Reactive Signal Binding (ZCZS Layer)
 * Subscribes a CSS property on an element to a reactive signal via runtime.effect().
 * On every signal tick, performs a targeted deleteRule + insertRule on jitSheet
 * to update the atomic rule in-place with zero layout jitter.
 */
export function adoptSignalBinding(
  element: HTMLElement,
  utilityPrefix: string,
  signalBindingKey: string,
  runtime: RuntimeContext
): void {
  const propertyTranslation: Record<string, string> = {
    w: 'width', h: 'height', p: 'padding', m: 'margin', gap: 'gap'
  };
  const cssTargetProperty = propertyTranslation[utilityPrefix];
  if (!cssTargetProperty) return;

  const atomicClassName = `nx-zczs-${utilityPrefix}-${signalBindingKey.replace(/[^a-zA-Z0-9]/g, '_')}`;

  runtime.effect(() => {
    const derivedValue = runtime.evaluate(element, signalBindingKey);
    const dynamicRule = `.${atomicClassName}{${cssTargetProperty}:calc(var(--spacing) * ${derivedValue});}`;

    const ruleSelector = `.${atomicClassName}`;
    let matchedIndex = -1;

    for (let i = 0; i < jitSheet.cssRules.length; i++) {
      const rule = jitSheet.cssRules[i] as CSSStyleRule;
      if (rule.selectorText === ruleSelector) {
        matchedIndex = i;
        break;
      }
    }

    if (matchedIndex === -1) {
      jitSheet.insertRule(dynamicRule, jitSheet.cssRules.length);
      element.classList.add(atomicClassName);
    } else {
      jitSheet.deleteRule(matchedIndex);
      jitSheet.insertRule(dynamicRule, matchedIndex);
    }
  });
}

// ── Bootstrapping JIT engine registries after all declarations (Section 6) are bound ──
populateStandardUtilities(designSystem);
populateStandardVariants(designSystem);

