/**
 * AOT-Injected Style Layer Constants
 *
 * This file is generated by scripts/build.ts during the AOT style layer
 * generation phase. It contains packed CSS strings for framework-specific
 * component classes and animation keyframes.
 *
 * ZCZS Role:
 *   - Zero-copy: These strings are adopted directly into constructable
 *     stylesheets without parsing or transformation.
 *   - Zero-serialization: Packed format minimizes string overhead while
 *     preserving CSSOM compatibility.
 *
 * Coordination:
 *   - Generated by build.ts fetchStyleLayerPrimitives()
 *   - Consumed by modules/attributes/stylesheet.ts for CSS adoption
 *   - Embedded in dist bundles via inline manifest concatenation
 *
 * Nexus-UX Innovation:
 *   - PACKED_COMPONENTS provides framework-specific drag-drop and UI
 *     state classes without external CSS dependencies.
 *   - PACKED_KEYFRAMES provides built-in animation primitives.
 */
export const PACKED_COMPONENTS = ".draggable-chosen{background-color:var(--color-base-300,#d4d4d8);box-shadow:inset 0 0 0 2px var(--color-primary,#3b82f6)}.draggable-drag{opacity:1;background-color:var(--color-base-300,#d4d4d8);box-shadow:0 25px 50px -12px rgba(0,0,0,.25);transform:scale(1.05);cursor:grabbing;z-index:9999}.draggable-ghost{opacity:1;background-color:var(--color-base-300,#d4d4d8);border:2px solid var(--color-primary,#3b82f6);box-shadow:0 25px 50px -12px rgba(0,0,0,.25)}.draggable-selected{box-shadow:inset 0 0 0 2px var(--color-accent,var(--color-secondary,#ec4899))}.draggable-swap-highlight{background-color:color-mix(in srgb,var(--color-warning,#eab308) 20%,transparent);box-shadow:inset 0 0 0 2px var(--color-warning,#eab308)}.drop-target-before{background:linear-gradient(to bottom,color-mix(in srgb,var(--color-primary,#3b82f6) 30%,transparent) 0%,transparent 20%);box-shadow:inset 0 2px 0 0 var(--color-primary,#3b82f6)}.drop-target-after{background:linear-gradient(to top,color-mix(in srgb,var(--color-primary,#3b82f6) 30%,transparent) 0%,transparent 20%);box-shadow:inset 0 -2px 0 0 var(--color-primary,#3b82f6)}";
export const PACKED_KEYFRAMES = "@keyframes spin{to{transform:rotate(360deg)}}@keyframes ping{75%,100%{transform:scale(2);opacity:0}}@keyframes pulse{50%{opacity:.5}}@keyframes bounce{0%,100%{transform:translateY(-25%);animation-timing-function:cubic-bezier(.8,0,1,1)}50%{transform:none;animation-timing-function:cubic-bezier(0,0,.2,1)}}";
