import * as esbuild from "esbuild";
import { denoPlugins } from "esbuild-deno-loader";
import * as path from "std/path";

interface BuildOptions {
  outputName?: string;
  excludeModules?: string[];
  gitRef?: string;
}

/**
 * Builds the Nexus-UX bundle with optional git history, custom naming, and tree shaking.
 */
async function buildBundle(options: BuildOptions = {}) {
  const { outputName = "nexus-ux", excludeModules = [], gitRef } = options;
  
  // If gitRef is specified, checkout that commit temporarily
  let originalCwd = Deno.cwd();
  if (gitRef) {
    const result = await new Deno.Command("git", {
      args: ["rev-parse", "--verify", gitRef],
      cwd: originalCwd,
    }).output();
    
    if (!result.success) {
      throw new Error(`Git ref '${gitRef}' not found`);
    }
  }
  
  try {
    await Deno.mkdir("./dist", { recursive: true });

    const cwd = Deno.cwd();
    const entryPoint = path.resolve(cwd, "src", "index.ts");
    const outFile = path.resolve(cwd, "dist", `${outputName}.js`);
    const configPath = path.resolve(cwd, "deno.json");

    const manifestPath = path.resolve(cwd, "src", "manifest.ts");
    const manifestJsonPath = path.resolve(cwd, "dist", "manifest.json");
    const assetsPath = path.resolve(cwd, "src", "engine", "assets.ts");

    const manifestLines = [
      "// AUTO-GENERATED BY scripts/build.ts",
      "import type { AttributeModule } from './engine/modules.ts';",
    ];
    let counter = 0;

    const manifestJsonData: Record<string, string[]> = {
      attributes: [],
      sprites: [],
      scopes: [],
      modifiers: [],
      observers: []
    };

    async function generateRegistry(
      dir: string, 
      exportName: string, 
      jsonKey: string,
      excludeList: string[] = []
    ) {
      const arr: string[] = [];
      try {
        const fullPath = path.resolve(cwd, "src", dir);
        for await (const entry of Deno.readDir(fullPath)) {
          if (entry.isFile && entry.name.endsWith(".ts") && entry.name !== "index.ts") {
            const nameWithoutExt = entry.name.replace(".ts", "");
            // Tree shaking: skip excluded modules
            if (excludeList.includes(nameWithoutExt)) {
              console.log(`  [Tree-shaken] ${dir}/${entry.name}`);
              continue;
            }
            const modName = `mod_${counter++}`;
            manifestLines.push(`import * as ${modName} from './${dir}/${entry.name}';`);
            arr.push(`{ name: '${nameWithoutExt}', module: ${modName} }`);
            manifestJsonData[jsonKey].push(nameWithoutExt);
          }
        }
      } catch(e) { /* ignore if dir missing */ }
      
      manifestLines.push("");
      manifestLines.push(`export const ${exportName}: any[] = [`);
      manifestLines.push(`  ${arr.join(',\n  ')}`);
      manifestLines.push("];");
    }

    await generateRegistry("modules/attributes", "autoAttributes", "attributes", excludeModules);
    await generateRegistry("modules/sprites", "autoSprites", "sprites", excludeModules);
    await generateRegistry("modules/scopes", "autoScopes", "scopes", excludeModules);
    await generateRegistry("modules/modifiers", "autoModifiers", "modifiers", excludeModules);
    
    // Mutation observer - static import like other engine files
    const mutationPath = path.resolve(cwd, "src", "engine", "mutation.ts");
    try {
      const stat = await Deno.stat(mutationPath);
      if (stat.isFile && !excludeModules.includes("mutation")) {
        manifestLines.push("");
        manifestLines.push("// Mutation observer module");
        manifestLines.push("import * as mod_mutation from './engine/mutation.ts';");
        manifestLines.push("export const autoObservers: any[] = [");
        manifestLines.push("  { name: 'mutation', module: mod_mutation }");
        manifestLines.push("];");
        manifestJsonData["observers"].push("mutation");
      } else {
        manifestLines.push("");
        manifestLines.push("export const autoObservers: any[] = [];");
      }
    } catch {
      manifestLines.push("");
      manifestLines.push("export const autoObservers: any[] = [];");
    }

    await Deno.writeTextFile(manifestPath, manifestLines.join("\n"));
    console.log("Generated manifest:", manifestPath);

    await Deno.writeTextFile(manifestJsonPath, JSON.stringify(manifestJsonData, null, 2));
    console.log("Generated JSON manifest:", manifestJsonPath);

    // Read CSS files and generate assets.ts with inline strings
    const assetsDir = path.resolve(cwd, "src", "engine", "assets");
    const cssFiles = ["index.css", "preflight.css", "theme.css", "utilities.css"];
    const assetEntries = [];
    
    for (const file of cssFiles) {
      try {
        const content = await Deno.readTextFile(path.join(assetsDir, file));
        const exportName = file.replace(".css", "");
        const escaped = content
          .replace(/\\/g, "\\\\")
          .replace(/`/g, "\\`")
          .replace(/\$\{/g, "\\${");
        assetEntries.push(`  ${exportName}: \`${escaped}\``);
      } catch {
        console.warn(`Warning: Could not read ${file}, skipping`);
      }
    }

    const assetsContent = `/**
 * Tailwind CSS Assets - AUTO-GENERATED
 * Bundled CSS files from Tailwind v4 (Oxide) engine.
 */

export const tailwindAssets = {
${assetEntries.join(",\n")}
} as const;

export type TailwindAssetName = keyof typeof tailwindAssets;
`;

    await Deno.writeTextFile(assetsPath, assetsContent);
    console.log("Generated assets:", assetsPath);

    // Build using ESBuild
    console.log("Starting esbuild...");
    await esbuild.build({
      plugins: [...denoPlugins({ configPath })],
      entryPoints: [entryPoint],
      outfile: outFile,
      bundle: true,
      format: "iife",
      globalName: "NexusLib",
      target: "es2022",
    });
    console.log(`Build complete: ${outFile}`);
  } catch (e) {
    console.error("Build failed:", e);
    throw e;
  } finally {
    esbuild.stop();
  }
}

/**
 * Batch build multiple configurations.
 */
async function batchBuild(configs: BuildOptions[]) {
  for (const config of configs) {
    console.log(`\n=== Building: ${config.outputName || 'default'} ===`);
    if (config.excludeModules?.length) {
      console.log(`  Excluded modules: ${config.excludeModules.join(", ")}`);
    }
    if (config.gitRef) {
      console.log(`  Git ref: ${config.gitRef}`);
    }
    await buildBundle(config);
  }
}

// Parse CLI arguments
const args = Deno.args;
if (args.includes("--batch")) {
  // Batch mode: read config from stdin or file
  const configFile = args.find(a => a.startsWith("--config="))?.split("=")[1];
  if (configFile) {
    const configData = JSON.parse(await Deno.readTextFile(configFile));
    await batchBuild(configData.configs || []);
  } else {
    console.error("Batch mode requires --config=file.json");
    Deno.exit(1);
  }
} else {
  // Single build mode
  const outputName = args.find(a => a.startsWith("--name="))?.split("=")[1];
  const excludes = args.find(a => a.startsWith("--exclude="))?.split("=")[1]?.split(",");
  const gitRef = args.find(a => a.startsWith("--ref="))?.split("=")[1];
  
  await buildBundle({
    outputName,
    excludeModules: excludes,
    gitRef,
  });
}

// Export for programmatic use
export { buildBundle, batchBuild };