import * as esbuild from "esbuild";
import { denoPlugins } from "esbuild-deno-loader";
import * as path from "std/path";

try {
  await Deno.mkdir("./dist", { recursive: true });

  const entryPoint = path.resolve(Deno.cwd(), "src", "index.ts");
  const outFile = path.resolve(Deno.cwd(), "dist", "nexus-ux.js");
  const configPath = path.resolve(Deno.cwd(), "deno.json");

  const manifestPath = path.resolve(Deno.cwd(), "src", "manifest.ts");
  const manifestJsonPath = path.resolve(Deno.cwd(), "dist", "manifest.json");

  const manifestLines = [
    "// AUTO-GENERATED BY scripts/build.ts",
    "import type { AttributeModule } from './engine/modules.ts';",
  ];
  let counter = 0;

  const manifestJsonData: Record<string, string[]> = {
    attributes: [],
    sprites: [],
    scopes: [],
    modifiers: [],
    observers: []
  };

  async function generateRegistry(dir: string, exportName: string, jsonKey: string) {
    const arr: string[] = [];
    try {
      const fullPath = path.resolve(Deno.cwd(), "src", dir);
      for await (const entry of Deno.readDir(fullPath)) {
        if (entry.isFile && entry.name.endsWith(".ts") && entry.name !== "index.ts") {
          const modName = `mod_${counter++}`;
          manifestLines.push(`import * as ${modName} from './${dir}/${entry.name}';`);
          const nameWithoutExt = entry.name.replace(".ts", "");
          arr.push(`{ name: '${nameWithoutExt}', module: ${modName} }`);
          manifestJsonData[jsonKey].push(nameWithoutExt);
        }
      }
    } catch(e) { /* ignore if dir missing */ }
    
    manifestLines.push("");
    manifestLines.push(`export const ${exportName}: any[] = [`);
    manifestLines.push(`  ${arr.join(',\n  ')}`);
    manifestLines.push("];");
  }

  await generateRegistry("modules/attributes", "autoAttributes", "attributes");
  await generateRegistry("modules/sprites", "autoSprites", "sprites");
  await generateRegistry("modules/scopes", "autoScopes", "scopes");
  await generateRegistry("modules/modifiers", "autoModifiers", "modifiers");
  await generateRegistry("engine/observers", "autoObservers", "observers");

  await Deno.writeTextFile(manifestPath, manifestLines.join("\n"));
  console.log("Generated manifest:", manifestPath);

  await Deno.writeTextFile(manifestJsonPath, JSON.stringify(manifestJsonData, null, 2));
  console.log("Generated JSON manifest:", manifestJsonPath);

  // Step 2: Bundle Using ESBuild

  await esbuild.build({
    plugins: [...denoPlugins({ configPath })],
    entryPoints: [entryPoint],
    outfile: outFile,
    bundle: true,
    format: "iife",
    globalName: "NexusLib",
    target: "es2022",
  });
  console.log("Build complete: dist/nexus-ux.js");
} catch (e) {
  console.error("Build failed:", e);
  Deno.exit(1);
} finally {
  esbuild.stop();
}
